[
  {
    id: 1,
    name: "Software Consultant",
    category: "Product Management",
    min_salary: 1965,
    max_salary: 4747,
  },
  {
    id: 2,
    name: "Speech Pathologist",
    category: "Research and Development",
    min_salary: 1395,
    max_salary: 4905,
  },
  {
    id: 3,
    name: "Research Nurse",
    category: "Business Development",
    min_salary: 1037,
    max_salary: 4790,
  },
  {
    id: 4,
    name: "Payment Adjustment Coordinator",
    category: "Sales",
    min_salary: 1049,
    max_salary: 4439,
  },
  {
    id: 5,
    name: "Programmer IV",
    category: "Marketing",
    min_salary: 1090,
    max_salary: 4071,
  },
  {
    id: 6,
    name: "Associate Professor",
    category: "Product Management",
    min_salary: 1704,
    max_salary: 4291,
  },
  {
    id: 7,
    name: "Executive Secretary",
    category: "Services",
    min_salary: 1631,
    max_salary: 4252,
  },
  {
    id: 8,
    name: "Environmental Specialist",
    category: "Business Development",
    min_salary: 1382,
    max_salary: 4258,
  },
  {
    id: 9,
    name: "VP Quality Control",
    category: "Legal",
    min_salary: 1610,
    max_salary: 4498,
  },
  {
    id: 10,
    name: "Engineer IV",
    category: "Support",
    min_salary: 1221,
    max_salary: 4974,
  },
];
